### ISSUE TITLE
No app icon on Linux

### ISSUE THREAD

**Issue by tiotrom** [digimezzo/knowte#110]
I am using the latest appimage and there is no icon for the app...
![image](https://user-images.githubusercontent.com/34804533/80323044-37d58c00-8829-11ea-84c8-beccb593949d.png)

Is there a simple way to fix it? Cheers!

**Comment by digimezzo** [comment]
@tiotrom Is this Manjaro? How did you install the AppImage? Are you using AppImageLauncher?
I'm adding following link for myself, for further investigation: https://github.com/electron-userland/electron-builder/issues/4617

**Comment by tiotrom** [comment]
Yes it is a Manjaro spin  (almost entirely Manjaro) + AppImageLauncher

**Comment by digimezzo** [comment]
@tiotrom Thanks for this info. I'll look into it. The link that I attached to this issue seems to point in the right direction.
