### ISSUE TITLE
Package it as flatpak, snap, or AUR?

### ISSUE THREAD

**Issue by tiotrom** [digimezzo/knowte#112]
Do you plan to package it to any of those formats? Flatpaks especially seem to get very poplar nowadays and many Linux distributions ship with flatpak support. Cheers!

**Comment by digimezzo** [comment]
@tiotrom  I definitely want to provide more package formats, but I need to look into the details.

**Comment by tiotrom** [comment]
We have a custom Linux distribution called TROMjaro (tromjaro.com) and we enabled flatpaks by default. We are based on Arch. We are looking for a default note taking app for our users and we kinda love yours so we want to include it in our default installation but at this time we rely on AUR or flatpaks to do so. If we have the time we could try helping you package it as one or the other. I am curious to see the new updates first to see how it integrates into the system ;). Again, super cool app you made!

**Comment by digimezzo** [comment]
@tiotrom Version 2.0.3 is available in the snap store. I'm now figuring out how to publish to AUR.

**Comment by tiotrom** [comment]
Great! I see you mentioned in the release "Added pacman and snap packages" - I was wondering do you mean you added an AUR package? if so here? Cheers!

**Comment by digimezzo** [comment]
@tiotrom I added a pacman package to the release downloads. I must admit that I don't understand AUR yet. I've read the AUR wiki on how to create and publish AUR packages and all I can see is that it seems centered around PKGBUILD files, and that people have to build AUR pacakges themselves? Currently, it is not straight forward for me on how to provide AUR support.

**Comment by tiotrom** [comment]
In fact it should be easy now that you have an appimage. Take a look at one of such apps made out of an appimage https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jitsi-meet-desktop-bin - you need a pkgfile that basically uses the appimage you already have. Unfortunately I am not very knowledgeable at this but I'll ping a friend who helps with our custom Linux distro and who made that AUR package maybe he can help.

**Comment by digimezzo** [comment]
@tiotrom Thanks for the hint. I think I can figure it out with this info :)

**Comment by digimezzo** [comment]
@tiotrom Knowte is now in the AUR: https://aur.archlinux.org/packages/knowte/
Thanks a lot for your help! :)

**Comment by tiotrom** [comment]
Oh thank you so much. I love it! And now we are thinking to include it as the default note taking app in our custom Linux distro TROMjaro (tromjaro.com). I already added it to our apps section here https://www.tromjaro.com/knowte/ - much appreciated sir!

**Comment by digimezzo** [comment]
@tiotrom You're welcome! And, thank you for adding Knowte to your apps section :)
