### ISSUE TITLE
Integrating a spellchecker?

### ISSUE THREAD

**Issue by tiotrom** [digimezzo/knowte#123]
I was wondering if this would be possible, to integrate a spellchecker.

**Comment by NoobAndProud-01** [comment]
Just my 2$ (can't find the cent thing) I assume most people use Knowte for quick notes, I do, so a spellchecker wouldn't be that useful. 

Now, if the dev could code a OneNote killer that would be awesome!

**Comment by digimezzo** [comment]
Related to #172 and implemented. Coming in version 3.0.0.
