### ISSUE TITLE
Create a personal server side component

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/Knowte#13]
Knowte should have a server side component, which allows saving notes in an online database. It should expose a REST API for access to notes.

**Comment by EMLVIRUS** [comment]
In that case, you should introduce Privacy Terms.

**Comment by digimezzo** [comment]
@EMLVIRUS I plan to provide a personal server side component. That each user can set up its own server. I'm not planning to set up a public server. So no privacy terms required.

**Comment by Rictusempra** [comment]
@digimezzo Have you considered to try to support personal cloud storage like OneDrive, Google Drive, Dropbox, Yandex, (S)FTP, WebData and all that?

**Comment by digimezzo** [comment]
@Rictusempra That's already implemented. Check Settings > Advanced > Storage. You can change the storage location of you notes to a cloud directory.

**Comment by Rictusempra** [comment]
I mean to access online API. This will be convenient for those who has not client

**Comment by digimezzo** [comment]
A plugin system is being created in #39. This will allow anyone to create custom plugin DLL's. The plugins will be loaded automatically. By default, a PHP MySQL API will be provided.
