### ISSUE TITLE
Make the sidebar resizable

### ISSUE THREAD

**Issue by harshithjv** [digimezzo/knowte#137]
Sidebar does not resize along with rest of window. No option to resize manually too.

Also it can be toggled to hide like slender column  with icons.

![image](https://user-images.githubusercontent.com/809278/89858616-bd086500-dbbc-11ea-8393-8e1f2e87838c.png)

_Note:_ Using on Ubuntu 18.04.

**Comment by harshithjv** [comment]
@digimezzo Thanks for considering this as enhancement. :)

**Comment by harshithjv** [comment]
@digimezzo  I checked with `v2.0.5`. The issue still persists.

**Comment by digimezzo** [comment]
@harshithjv I know :) It's planned for version 2.0.6. You can see the planned version on the sidebar on the right of this page.

**Comment by digimezzo** [comment]
Fixed in 94a22490e428d2a4f9a9e84311e774c1b7e2b8e9
