### ISSUE TITLE
Where are old Knowte note files located?

### ISSUE THREAD

**Issue by bangaroodong** [digimezzo/knowte#138]
I updated from v1.1.7 to v2.0.4 and all my notes are missing now.
What kind of files can I search for? Or are they all gone for sure?

**Comment by bangaroodong** [comment]
nevermind, realized that v1.1.7 is still installed and still alot better than v2.0.4 anyway :)

**Comment by digimezzo** [comment]
@bangaroodong Could you let me know in what way 1.1.7 is better than 2.0.x? At least I could try to improve it. Thanks.

**Comment by digimezzo** [comment]
> @bangaroodong Could you let me know in what way 1.1.7 is better than 2.0.x? At least I could try to improve it. Thanks.

I guess not. That is unfortunate.
