### ISSUE TITLE
Can't import notes

### ISSUE THREAD

**Issue by dragosani24** [digimezzo/knowte#139]
Hi! When I try to import some export notes give me this error from logs: 

`[error] [CollectionService] [importNoteFilesAsync] An error occurred while importing note file '~/file.knowte'. Cause: SyntaxError: Unexpected token o in JSON at position 1`

What can I do?

**Comment by letianwuji** [comment]
[2020-10-08 17:51:59.343] [info] [CollectionService] [importFromOldVersionAsync] D:\tool\Knowte\Knowte\Notes\Notes.json was not found. Not importing notes.

**Comment by digimezzo** [comment]
@dragosani24 That's indeed a bug. I'm looking into it.

**Comment by digimezzo** [comment]
@letianwuji Your problem seems different. Did you export your notes from Knowte 1.x? The export should create 2 files: Notebooks.json and Notes.json.

When importing in Knowte 2, you should select the folder that contains these 2 files.

**Comment by digimezzo** [comment]
@dragosani24 Knowte 2.0.5 will be released this weekend and will fix this bug. Please keep an eye on it.

**Comment by digimezzo** [comment]
@dragosani24 Knowte 2.0.5 has just been released and fixed your issue.
