### ISSUE TITLE
Add i18n for German language [enhancement]

### ISSUE THREAD

**Issue by ffatgit** [digimezzo/knowte#140]
Hello diggimezzo,

I'm not so the "coder nerd" so I'm not so into the git thing (so I wasn't successful to make a usual "Pull requests").
But I'd like to contribute in form of the translation of "knowte V2.0.5".
The translation is done in the German personal "buddy" style instead of the "official" style; e.g.:
- "buddy" = You diggimezzo
- "official" = You Mr. diggimezzo sir
Hope that is okay. 
If not, give me a feedback and I will do it in the "offiicial" style. 
So please be so kind to use the attached file "de.txt" and rename it to "de.json".
Hope this is okay - sorry for this "way".
Thank you for your great work so far!

Best regards
FF

[de.txt](https://github.com/digimezzo/knowte/files/5410361/de.txt)

**Comment by digimezzo** [comment]
@ff Thank you! I'll add this translation to Knowte 2.0.6. I think "buddy" style should be fine. I try to keep the translations friendly for the user. So I don't believe my other translations are really formal.
