### ISSUE TITLE
Add Chinese Language, Please

### ISSUE THREAD

**Issue by Mosaic67** [digimezzo/knowte#143]

**Comment by digimezzo** [comment]
@Mosaic67 I'd love to add Chinese. However, I'll need a Chinese translator for this. Can you help? The translation files are here: https://github.com/digimezzo/knowte/tree/master/src/assets/i18n. You can pick the en.json file, translate the texts and send it back to me, or via a pull request.

**Comment by Mosaic67** [comment]
@digimezzo I initiated a pull request #147, Please check.

**Comment by digimezzo** [comment]
Fixed in a7f68153c6e93ce537bb8c9dd2a10f4135622430
