### ISSUE TITLE
App ignores the CTRL + Y. Need the ability to redo (text in notes).

### ISSUE THREAD

**Issue by IT-Tool** [digimezzo/knowte#145]
Hello diggimezzo,

If I edit the note and want to undo changes, I use the CTRL + Z, but if pressing this key was wrong or I want to redo it, the application ignores the CTRL + Y key combination (same thing on Linux and Windows). Which means that the text has been lost, it's not convenient.

How about adding the redo feature?

Or maybe to add the option in settings to save the history of changes (anything that will increase the reliability of storing notes in this app).

Thank you for your projects

**Comment by digimezzo** [comment]
@IT-Tool Thank you for liking my projects. That's annoying that Knowte is ignoring CTRL+Y for you. I tried it out here, but I don't have the issue. Both CTRL+Y and CTRL+SHIFT+Z redoes an action here. Maybe it is a combination of action that causes this issue. Coudl you add some details on the action that your perform before pressing CTRL+Z or CTRL+Y? Thank you.

**Comment by IT-Tool** [comment]
You right. I noticed that different programs use different combinations for Redo.
![Screenshot at 2020-11-20](https://user-images.githubusercontent.com/53435741/99835951-4684e700-2b5d-11eb-8262-28817a676279.png)

But Redo in Knowte didn't work by pressing CTRL + Z on Linux Mint 19.3 and Windows 10. 

Now I will use this combination CTRL+SHIFT+Z
1. But if we imagine that a person does not know about these combination. The text will be lost (also no buttons for Undo and Redo are provided in the program interface).
2. If you delete text in note and close the window (maybe it was an accident), after open note again nothing can be Redo (even if you know combination that works) :) Text in that note is lost again.

It's not cool scenario. I hope its can be improved :)
* add buttons for Undo and Redo
* save the history of note changes
* or anything else.

Thanks anyway!
