### ISSUE TITLE
Trash bin

### ISSUE THREAD

**Issue by MarioVB** [digimezzo/knowte#146]
Hi! 
Last night i erased a very important note and just realized that there is no trash bin. 

Is there someone working on it? I'd never made a pull request or contribution on free software. Still want to contribute or follow someone's steps throught. I would be very greatful.

Thank you

**Comment by digimezzo** [comment]
@MarioVB Hi! Thank you for reporting this. This is similar to issue #44. I'll give this priority, as this is a very critical feature. I'm starting to work on it and it I'll be in the next version (I think I can have this ready in a week).

**Comment by digimezzo** [comment]
Fixed in 7a280bb40ce530bde2aa44d3de2654faacdf4a4d
