### ISSUE TITLE
Light colored header

### ISSUE THREAD

**Issue by SilverMarcs** [digimezzo/knowte#155]
Just found this app and its really cool, especially with the ability to add images from clipboard. However the dark headerbar (the one that says today yesterday etc and also the one that shows note title in notes view) mekes it stick out a lot in light themes. For example in gnome adwaita theme, the black bar kills coherence. Perhaps make that something similar to the page white color? Or at least provide a choice. Would be super cool thanks

**Comment by digimezzo** [comment]
@SilverMarcs Good idea! I'm planning this for the next release.

**Comment by digimezzo** [comment]
@SilverMarcs I've made these change. The default header bar is still dark, but there is an option to have a light header bar. This is how it looks with Adwaita. Is this what you had in mind?

![image](https://user-images.githubusercontent.com/11945339/127734374-0d369385-428f-416c-910f-4cd8f06e63c0.png)
![image](https://user-images.githubusercontent.com/11945339/127734399-c5529440-8b34-4105-9100-980ff3f8aa64.png)

**Comment by SilverMarcs** [comment]
This is precisely what I suggested. Thanks, great work!

**Comment by digimezzo** [comment]
@SilverMarcs Thanks! I'll release this tomorrow. Stay tuned :)
