### ISSUE TITLE
Search in the note

### ISSUE THREAD

**Issue by PenguinAnt** [digimezzo/knowte#160]
Hello,
It would be interesting to be able to search within a note with Ctrl+F.
Tanks!

**Comment by PenguinAnt** [comment]
Hello,
I was able to use the search function several times with Ctrl+F from the home page of the software (All notes). It does the job. However, if you are already in a note and you want to do a search (if the note is long, so), you have to leave it to do the search and the possibly unwanted results of other notes are displayed in this case.
Rgds

**Comment by digimezzo** [comment]
Hi! This is planned for the next version (It's currently in development); https://github.com/digimezzo/knowte/milestone/11
