### ISSUE TITLE
Bug: Import from Knowte 1.x simply don't work

### ISSUE THREAD

**Issue by bbbiy** [digimezzo/knowte#180]
This Ubuntu update was literally the worst thing that ever happened, and I lost 3 years of college notes because Knowte cant read all the ".state" and ".content" files they used to.

Im trying to fix this but I think its an internal bug

**Comment by digimezzo** [comment]
I'll most likely be able to help you out if you give me some more details. Which actions did you performed and what happened?

**Comment by digimezzo** [comment]
I'm closing this issue, by lack of details.
