### ISSUE TITLE
[Feature Request] Text editor

### ISSUE THREAD

**Issue by MulverineX** [digimezzo/Knowte#28]
I realize this would be a big update but, it would be nice if knowte could edit any text file and perhaps have highlighting for code and space tabing. This might end up being another program but I would love a text editor in the same style as the rest of digimezzo programs.

**Comment by digimezzo** [comment]
This will not be implemented for Knowte. Another text editor with this capability will probably not be created by Digimezzo, as it would be very time consuming to get at the same level as existing text editors.
