### ISSUE TITLE
Add Markdown support

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/knowte#99]
It should be possible to create and edit notes using Markdown.

**Comment by geira** [comment]
+1 for this. I've been using [nvAlt](https://brettterpstra.com/projects/nvalt/) on the Mac for years (and Notational Velocity before that), a Linux compatible app have been requested for years. The workflow of editing Markdown files in a single Dropbox folder works seamlessly across platforms (currently using Editorial on iOS, PlainText before that) with no sync problems. So far the only alternative for Linux is Typora, but that is commercial and more suitable for editing single documents.

**Comment by digimezzo** [comment]
Markdown support was added.
